version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eucomida
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  app:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - db
